### ISSUE TITLE
release title/name missing

### ISSUE THREAD

**Issue by ReenigneArcher** [RPCS3/rpcs3-binaries-linux#3]
Would it be possible to add a release title (name) for future releases like on the Windows binary?

I am using scripts and github api to automatically update RPCS3 (as well as other emulators). First I check the version output of the executable, parse it, and then compare it to the tag name. This works for the windows binaries, but not for the linux ones as the tag is missing.

My script is expecting the title in the format `0.0.19-13010`

Windows:
![image](https://user-images.githubusercontent.com/42013603/141709563-874cabf4-f4dd-4577-b5fd-9a5194759647.png)
![image](https://user-images.githubusercontent.com/42013603/141710068-5daf111d-6d79-4588-8d80-b9f36db408bf.png)

Linux:
![image](https://user-images.githubusercontent.com/42013603/141709529-c3f5fb43-f5b8-4e0f-98b0-f67b246355f1.png)
![image](https://user-images.githubusercontent.com/42013603/141710100-a51f036f-a0c6-48d9-9bf6-2018d852dce3.png)

**Comment by hcorion** [comment]
This issue has been fixed in the latest release
https://github.com/RPCS3/rpcs3-binaries-linux/releases/tag/build-f6a06a5618a87ab9bf55107a8a8ee5df6b08b186
Also in the future please report an issues with the build system in the main repo https://github.com/RPCS3/rpcs3/issues nobody checks the issues on this repo

**Comment by ReenigneArcher** [comment]
> This issue has been fixed in the latest release https://github.com/RPCS3/rpcs3-binaries-linux/releases/tag/build-f6a06a5618a87ab9bf55107a8a8ee5df6b08b186 Also in the future please report an issues with the build system in the main repo https://github.com/RPCS3/rpcs3/issues nobody checks the issues on this repo

Thanks! Maybe a suggestion would be to have an issue template `config.yml` that redirects users to the main repo. Something like this?

```yml
blank_issues_enabled: false
contact_links:
  - name: RPCS3 issue
    url: https://github.com/RPCS3/rpcs3/issues/new/choose
    about: Issues should be created in our main rpcs3 repository
```

Either way, thanks for fixing!
