### ISSUE TITLE
RPCS3 only runs on NVIDIA GPU?

### ISSUE THREAD

**Issue by seriousfreezing** [RPCS3/rpcs3-binaries-linux#4]
Every time I try to run the emulator through my Intel graphics card or even switch from Vulkan to OpenGL, it doesn't load my game and just doesn't respool.

**Comment by hcorion** [comment]
Hey there, please close this issue.
Nobody checks this issue tracker, if you have any issues with RPCS3, please file them on the main issue tracker on [RPCS3/rpcs3](https://github.com/RPCS3/rpcs3).
