### ISSUE TITLE
Verification failed

### ISSUE THREAD

**Issue by Zombar3** [RPCS3/rpcs3-binaries-linux#5]
SteamOS 3.3 Holoiso.
Yesterday i run Bourne, but today after yesterday's update i see this error and crashes.

Verification failed
(in file /run/build/rpcs3/rpcs3/Emu/CPU/CPUThread.cpp:1196[:2], in function cleanup) (errno=2=No such file or directory)
Thread id = 2.

**Comment by AniLeo** [comment]
This repository does not accept issue tickets.

https://github.com/RPCS3/rpcs3/issues/new/choose
