### ISSUE TITLE
Latest build doesn't have 'latest' tag.

### ISSUE THREAD

**Issue by ChTPwner** [RPCS3/rpcs3-binaries-linux#6]
I am trying to automate my RPCS3 install via Ansible.

When I call github's api to get the latest release it points to rpcs3-v0.0.18-12817-fff0c96b_linux64.AppImage

![image](https://user-images.githubusercontent.com/14848356/188284432-83a81428-f6c6-4725-ab97-39603f1caf88.png)

On the website, the latest release is rpcs3-v0.0.24-14112-64579eef_linux64.AppImage

**Comment by sonigfr** [comment]
Yes @ChTBoner it is someway not clean but on the website download section **https://rpcs3.net/download** you have surely the most official `curl -JLO https://rpcs3.net/latest-appimage` instruction.

**Comment by ChTPwner** [comment]
OK thank you, I will try that.

**Comment by rusak47** [comment]
Hello!
@sonigfr thank you, for useful link. 
I'm trying to automate aur pkgbuild and now i can easily retrieve the latest appimage, however i can't find a way how to retrieve submitted image checksum.

Please, could someone help with that?

**Comment by sonigfr** [comment]
@diabolusss I don't know if I well understand what you want but at the same address : https://rpcs3.net/download you have SHA-256 for each download type, as for Linux, current is  B5D37E473C333F3E46B0EDDA7CA25E7DF14F15D7BC3CD006A6263C47377871CF 
You can also retrieve this information on the github linux latest release : https://github.com/RPCS3/rpcs3-binaries-linux/releases/tag/build-4c8630d29fb154bb9ca196133f43799ec6423f5b 
If not sufficient, I recommend you to ask a developer of rpcs3 from their forum : https://forums.rpcs3.net or on github https://github.com/rpcs3 directly.

**Comment by rusak47** [comment]
@sonigfr I totally agree with you that visually, this information is available in listed sources. I'm just trying to figure out how to get this information via curl or in any similar way to automate aur PKGBUILD.
Now i have to manually fix sha256sums string in PKGBUILD, while everything else is retrieved automatically.

```$ cat PKGBUILD.rolling 
pkgname=rpcs3-bin
#https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-90d6069a1646efb054a3a921076ff37379518390/rpcs3-v0.0.24-14335-90d6069a_linux64.AppImage
_latest_appimage="$(curl --silent --dump-header - https://rpcs3.net/latest-appimage| grep -i '^location: ' |cut -d ' ' --fields 2| sed $'s/[^[:print:]\t]//g')"
#v0.0.24
pkgver=$(echo $_latest_appimage|awk -F- '{print $(NF-2)}')
#14335-90d6069a
_pkgbuild="$(echo ${_latest_appimage%_*} |awk -F- '{print $(NF-1)"-"$(NF)}')"
pkgrel=4
pkgdesc='Open-source Sony PlayStation 3 Emulator'
arch=('x86_64')
url='https://rpcs3.net/'
license=('GPL2')
depends=(...)
makedepends=('p7zip')
options=('!strip')
replaces=('rpcs3')
provides=('rpcs3')
conflicts=('rpcs3')
source=("$_latest_appimage")
#TODO#how to retrieve it automatically?
sha256sums=('d7eb44081bd2ed1885e161e453060fc887134d9c80c06cffe6ad714c28480b24')
prepare()
{   ...    }

package()
{   ...    }
```

**Comment by sonigfr** [comment]
@diabolusss curl -sL https://rpcs3.net/latest-appimage | sha256sum 🤷🏻‍♂️

**Comment by rusak47** [comment]
> @diabolusss curl -sL https://rpcs3.net/latest-appimage | sha256sum 🤷🏻‍♂️

Thank you, @sonigfr, but as far as i understand your suggestion is to compute checksum from curl output and to use it to bypass pkg checksum check while installing.
While it's an interesting workaround, it's not a suitable solution, because it completely nullifies this security measure.

**Comment by AniLeo** [comment]
This repository does not accept issue tickets.

https://github.com/RPCS3/rpcs3/issues/new/choose
